//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Portal_Task.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Examdb_newEntities : DbContext
    {
        public Examdb_newEntities()
            : base("name=Examdb_newEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblContent_questions> tblContent_questions { get; set; }
        public virtual DbSet<tblStudent_details> tblStudent_details { get; set; }
        public virtual DbSet<tblStudent_exam_questions> tblStudent_exam_questions { get; set; }
        public virtual DbSet<tblStudent_exams> tblStudent_exams { get; set; }
        public virtual DbSet<tblTopic_contents> tblTopic_contents { get; set; }
        public virtual DbSet<tblTopic> tblTopics { get; set; }
    }
}
