//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Portal_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContent_questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblContent_questions()
        {
            this.tblStudent_exam_questions = new HashSet<tblStudent_exam_questions>();
        }
    
        public int Question_id { get; set; }
        public Nullable<int> Content_id { get; set; }
        public string Question { get; set; }
        public string Option_1 { get; set; }
        public string Option_2 { get; set; }
        public string Option_3 { get; set; }
        public string Option_4 { get; set; }
        public Nullable<int> Correct_option_number { get; set; }
    
        public virtual tblTopic_contents tblTopic_contents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudent_exam_questions> tblStudent_exam_questions { get; set; }
    }
}
