//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Portal_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStudent_details()
        {
            this.tblStudent_exams = new HashSet<tblStudent_exams>();
        }
    
        public int Student_id { get; set; }
        public string Student_name { get; set; }
        public string Email_address { get; set; }
        public string Mobile_number { get; set; }
        public string Qualification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudent_exams> tblStudent_exams { get; set; }
    }
}
