//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Portal_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent_exam_questions
    {
        public int Exam_question_id { get; set; }
        public Nullable<int> Exam_id { get; set; }
        public Nullable<int> Question_id { get; set; }
        public Nullable<int> Submited_option_number { get; set; }
    
        public virtual tblContent_questions tblContent_questions { get; set; }
        public virtual tblStudent_exams tblStudent_exams { get; set; }
    }
}
