//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Portal_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent_exams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStudent_exams()
        {
            this.tblStudent_exam_questions = new HashSet<tblStudent_exam_questions>();
        }
    
        public int Exam_id { get; set; }
        public Nullable<int> Student_id { get; set; }
        public Nullable<int> Topic_id { get; set; }
        public Nullable<System.DateTime> Exam_date { get; set; }
        public string Start_time { get; set; }
        public string End_time { get; set; }
    
        public virtual tblStudent_details tblStudent_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudent_exam_questions> tblStudent_exam_questions { get; set; }
        public virtual tblTopic tblTopic { get; set; }
    }
}
