//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Portal_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTopic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTopic()
        {
            this.tblStudent_exams = new HashSet<tblStudent_exams>();
            this.tblTopic_contents = new HashSet<tblTopic_contents>();
        }
    
        public int Topic_id { get; set; }
        public string Topic_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudent_exams> tblStudent_exams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTopic_contents> tblTopic_contents { get; set; }
    }
}
