//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Portal_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTopic_contents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTopic_contents()
        {
            this.tblContent_questions = new HashSet<tblContent_questions>();
        }
    
        public int Content_id { get; set; }
        public string Content_name { get; set; }
        public Nullable<int> Topic_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContent_questions> tblContent_questions { get; set; }
        public virtual tblTopic tblTopic { get; set; }
    }
}
